// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9iF4DMNxdrEpQofVKeCH-ic6nU84NKSY',
    appId: '1:145343952875:web:9fb21ea0e2ba9266c90bae',
    messagingSenderId: '145343952875',
    projectId: 'company-app-44723',
    authDomain: 'company-app-44723.firebaseapp.com',
    storageBucket: 'company-app-44723.appspot.com',
    measurementId: 'G-0R6K0LJ9B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl2PfJxVT7U-kxfklnd0NfXtdjJLnW3ps',
    appId: '1:145343952875:android:a2a46ceaf5c8fc31c90bae',
    messagingSenderId: '145343952875',
    projectId: 'company-app-44723',
    storageBucket: 'company-app-44723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQKpw2fcZyqJo5HSqfh6iNxakQ_KOgepU',
    appId: '1:145343952875:ios:f17269af1206362fc90bae',
    messagingSenderId: '145343952875',
    projectId: 'company-app-44723',
    storageBucket: 'company-app-44723.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQKpw2fcZyqJo5HSqfh6iNxakQ_KOgepU',
    appId: '1:145343952875:ios:99e5c39d1fcd0dcdc90bae',
    messagingSenderId: '145343952875',
    projectId: 'company-app-44723',
    storageBucket: 'company-app-44723.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
